Repository kosSpringBoot2/geulkkoli, pull requests merged in 2023-04, with the labels that each got.

#11 Feature/#10 post delete
  geulkkoli/src/main/java/com/geulkkoli/domain/post/ImplPostRepository.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/PostController.java
  geulkkoli/src/test/java/com/geulkkoli/domain/post/ImplPostRepositoryTest.java
Labels: enhancement

#16 Feature/fix
  geulkkoli/src/main/java/com/geulkkoli/web/post/PostController.java
  geulkkoli/src/test/java/com/geulkkoli/domain/post/ImplPostRepositoryTest.java
Labels: bug

#17 Fix/post02
  geulkkoli/src/main/java/com/geulkkoli/web/post/PostController.java
Labels: bug

#23 feature/#20-postPageEdit :
  geulkkoli/src/main/resources/templates/post/postList.html
Labels: enhancement

#25 feature/#24-postAddFormEdit :
  geulkkoli/src/main/resources/templates/post/postAddForm.html
  geulkkoli/src/main/resources/templates/post/postPage.html
Labels: enhancement

#27 Feature/#26 post page edit
  geulkkoli/src/main/java/com/geulkkoli/TestDataInit.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/ImplPostRepository.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/Post.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/PostRepository.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/PostService.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/PostController.java
  geulkkoli/src/main/resources/templates/post/postEditForm.html
  geulkkoli/src/main/resources/templates/post/postList.html
  geulkkoli/src/main/resources/templates/post/postPage.html
Labels: enhancement

#30 Feature/#21 logout
  geulkkoli/src/main/java/com/geulkkoli/web/user/UserController.java
  geulkkoli/src/main/resources/static/css/bootstrap.min.css
  geulkkoli/src/main/resources/templates/footer.html
  geulkkoli/src/main/resources/templates/header.html
  geulkkoli/src/main/resources/templates/index.html
  geulkkoli/src/main/resources/templates/user/joinForm.html
Labels: enhancement

#31 #6 fix : PRG패턴 적용 & 헤더 변경 & 인덱스용 홈 컨트롤러
  geulkkoli/src/main/java/com/geulkkoli/web/home/HomeController.java
  geulkkoli/src/main/java/com/geulkkoli/web/user/UserController.java
  geulkkoli/src/main/resources/templates/header.html
Labels: bug

#34 #33 feat, refactor : 회원 탈퇴 기능 구현 및 유저 관련 서비스 유저 서비스로 통합
  geulkkoli/src/main/java/com/geulkkoli/domain/user/ImplUserRepository.java
  geulkkoli/src/main/java/com/geulkkoli/domain/user/UserRepository.java
  geulkkoli/src/main/java/com/geulkkoli/domain/user/service/LoginService.java
  geulkkoli/src/main/java/com/geulkkoli/domain/user/service/UserService.java
  geulkkoli/src/main/java/com/geulkkoli/web/user/UserController.java
  geulkkoli/src/test/java/com/geulkkoli/domain/user/service/LoginServiceTest.java
Labels: enhancement

#35 Feature/#32 add form nickname
  geulkkoli/src/main/java/com/geulkkoli/TestDataInit.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/ImplPostRepository.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/Post.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/PostService.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/service/PostService.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/PostController.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/dto/AddDTO.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/dto/EditDTO.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/dto/ListDTO.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/dto/PageDTO.java
  geulkkoli/src/main/resources/schema.sql
  geulkkoli/src/main/resources/templates/header.html
  geulkkoli/src/main/resources/templates/post/postAddForm.html
  geulkkoli/src/main/resources/templates/post/postList.html
  geulkkoli/src/test/java/com/geulkkoli/domain/post/ImplPostRepositoryTest.java
Labels: enhancement

#37 Feature/#36 post page author
  geulkkoli/src/main/java/com/geulkkoli/TestDataInit.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/ImplPostRepository.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/Post.java
  geulkkoli/src/main/java/com/geulkkoli/domain/user/service/UserService.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/PostController.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/dto/AddDTO.java
  geulkkoli/src/main/java/com/geulkkoli/web/post/dto/PageDTO.java
  geulkkoli/src/main/resources/static/images/defaultProfile.png
  geulkkoli/src/main/resources/templates/post/postAddForm.html
  geulkkoli/src/main/resources/templates/post/postEditForm.html
  geulkkoli/src/main/resources/templates/post/postList.html
  geulkkoli/src/main/resources/templates/post/postPage.html
  geulkkoli/src/test/java/com/geulkkoli/domain/post/ImplPostRepositoryTest.java
  geulkkoli/src/test/java/com/geulkkoli/domain/post/PostRepositoryTest.java
  geulkkoli/src/test/java/com/geulkkoli/domain/post/PostServiceTest.java
  geulkkoli/src/test/java/com/geulkkoli/infrastructure/PostRepositoryTest.java
Labels: enhancement

#40 시큐리티 일부분을 구현하였다.
  geulkkoli/build.gradle
  geulkkoli/src/main/java/com/geulkkoli/TestDataInit.java
  geulkkoli/src/main/java/com/geulkkoli/application/post/commitTest.txt
  geulkkoli/src/main/java/com/geulkkoli/application/security/UserSecurityService.java
  geulkkoli/src/main/java/com/geulkkoli/application/security/config/SecurityConfig.java
  geulkkoli/src/main/java/com/geulkkoli/application/security/handler/LoginFailureHandler.java
  geulkkoli/src/main/java/com/geulkkoli/application/user/AuthUser.java
  geulkkoli/src/main/java/com/geulkkoli/application/user/Role.java
  geulkkoli/src/main/java/com/geulkkoli/application/user/UserModelDto.java
  geulkkoli/src/main/java/com/geulkkoli/application/user/commitTest.txt
  geulkkoli/src/main/java/com/geulkkoli/domain/post/ImplPostRepository.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/Post.java
  geulkkoli/src/main/java/com/geulkkoli/domain/post/PostRepository.java
  geulkkoli/src/main/java/com/geulkkoli/domain/user/User.java
  geulkkoli/src/main/java/com/geulkkoli/domain/user/service/UserService.java
  geulkkoli/src/main/java/com/geulkkoli/web/user/JoinFormDto.java
  geulkkoli/src/main/java/com/geulkkoli/web/user/LoginFormDto.java
  geulkkoli/src/main/java/com/geulkkoli/web/user/UserController.java
  geulkkoli/src/main/resources/application.properties
  geulkkoli/src/main/resources/errors.properties
  geulkkoli/src/main/resources/errors_er_EN .properties
  geulkkoli/src/main/resources/errors_ko_KR.properties
  geulkkoli/src/main/resources/message.properties
  geulkkoli/src/main/resources/templates/header.html
  geulkkoli/src/main/resources/templates/index.html
  geulkkoli/src/main/resources/templates/post/postList.html
  geulkkoli/src/main/resources/templates/user/edit/editForm.html
  geulkkoli/src/main/resources/templates/user/loginForm.html
  geulkkoli/src/test/java/com/geulkkoli/application/SecurityTest.java
  geulkkoli/src/test/java/com/geulkkoli/domain/UserTest.java
  geulkkoli/src/test/java/com/geulkkoli/domain/user/service/LoginServiceTest.java
  geulkkoli/src/test/java/com/geulkkoli/domain/user/service/UserServiceTest.java
  geulkkoli/src/test/java/com/geulkkoli/infrastructure/UserRepositoryTest.java
  geulkkoli/src/test/java/com/geulkkoli/web/user/UserControllerTest.java
  geulkkoli/src/test/resources/application.properties
Labels: documentation, enhancement
